export const users =[
  {
    id: 1,
    "name": "Jan",
    "lastName": "Kowalski",
    "ratingCourse": "5",
    "ratingActive": "3",
    "ratingCode": "4",
    "ratingWork": "5",
    "preferPlaceWork": "Biuro",
    "cityWork": "Warszawa",
    "contractType": "Umowa o pracę",
    "expectedSalary": "8000",
    "freePractice": "Tak",
    "commercialExp": "6 miesięcy"
  },
  {
    id: 2,
    "name": "Paweł",
    "lastName": "Szymański",
    "ratingCourse": "5",
    "ratingActive": "3",
    "ratingCode": "4",
    "ratingWork": "5",
    "preferPlaceWork": "Biuro",
    "cityWork": "Warszawa",
    "contractType": "Umowa o pracę",
    "expectedSalary": "8000",
    "freePractice": "Tak",
    "commercialExp": "6 miesięcy"
  },
  {
    id: 3,
    "name": "Mariusz",
    "lastName": "Lipa",
    "ratingCourse": "5",
    "ratingActive": "3",
    "ratingCode": "4",
    "ratingWork": "5",
    "preferPlaceWork": "Biuro",
    "cityWork": "Warszawa",
    "contractType": "Umowa o pracę",
    "expectedSalary": "8000",
    "freePractice": "Tak",
    "commercialExp": "6 miesięcy"
  },
  {
    id: 4,
    "name": "Katarzyna",
    "lastName": "Kot",
    "ratingCourse": "5",
    "ratingActive": "3",
    "ratingCode": "4",
    "ratingWork": "5",
    "preferPlaceWork": "Biuro",
    "cityWork": "Warszawa",
    "contractType": "Umowa o pracę",
    "expectedSalary": "8000",
    "freePractice": "Tak",
    "commercialExp": "6 miesięcy"
  },
  {
    id: 5,
    "name": "Kamil",
    "lastName": "Olszewski",
    "ratingCourse": "5",
    "ratingActive": "3",
    "ratingCode": "4",
    "ratingWork": "5",
    "preferPlaceWork": "Biuro",
    "cityWork": "Warszawa",
    "contractType": "Umowa o pracę",
    "expectedSalary": "8000",
    "freePractice": "Tak",
    "commercialExp": "6 miesięcy"
  },
  {
    id: 6,
    "name": "Aleksandra",
    "lastName": "Maj",
    "ratingCourse": "5",
    "ratingActive": "3",
    "ratingCode": "4",
    "ratingWork": "5",
    "preferPlaceWork": "Biuro",
    "cityWork": "Warszawa",
    "contractType": "Umowa o pracę",
    "expectedSalary": "8000",
    "freePractice": "Tak",
    "commercialExp": "6 miesięcy"
  },
  {
    id: 7,
    "name": "Marcin",
    "lastName": "Przybylski",
    "ratingCourse": "5",
    "ratingActive": "3",
    "ratingCode": "4",
    "ratingWork": "5",
    "preferPlaceWork": "Biuro",
    "cityWork": "Warszawa",
    "contractType": "Umowa o pracę",
    "expectedSalary": "8000",
    "freePractice": "Tak",
    "commercialExp": "6 miesięcy"
  },
  {
    id: 8,
    "name": "Marcin",
    "lastName": "Nowak",
    "ratingCourse": "5",
    "ratingActive": "3",
    "ratingCode": "4",
    "ratingWork": "5",
    "preferPlaceWork": "Biuro",
    "cityWork": "Warszawa",
    "contractType": "Umowa o pracę",
    "expectedSalary": "8000",
    "freePractice": "Tak",
    "commercialExp": "6 miesięcy"
  },
  {
    id: 9,
    "name": "Łukasz",
    "lastName": "Kowalski",
    "ratingCourse": "5",
    "ratingActive": "3",
    "ratingCode": "4",
    "ratingWork": "5",
    "preferPlaceWork": "Biuro",
    "cityWork": "Warszawa",
    "contractType": "Umowa o pracę",
    "expectedSalary": "8000",
    "freePractice": "Tak",
    "commercialExp": "6 miesięcy"
  },
  {
    id: 10,
    "name": "Jakub",
    "lastName": "Nowak",
    "ratingCourse": "5",
    "ratingActive": "3",
    "ratingCode": "4",
    "ratingWork": "5",
    "preferPlaceWork": "Biuro",
    "cityWork": "Warszawa",
    "contractType": "Umowa o pracę",
    "expectedSalary": "8000",
    "freePractice": "Tak",
    "commercialExp": "6 miesięcy"
  }
]