interface Students {
    id: number
    name: string
    lastName: string
    ratingCourse: number
    ratingActive: number
    ratingCode: number
    ratingWork: number
    preferPlaceWork: string
    cityWork: string
    contractType: string
    expectedSalary: number
    freePractice: string
    commercialExp: string
    reservation: boolean
}

export const users: Students[] = [
    {
        id: 1,
        name: "Jan",
        lastName: "Kowalski",
        ratingCourse: 5,
        ratingActive: 3,
        ratingCode: 4,
        ratingWork: 5,
        preferPlaceWork: "Biuro",
        cityWork: "Warszawa",
        contractType: "Umowa o pracę",
        expectedSalary: 8000,
        freePractice: "Tak",
        commercialExp: "6 miesięcy",
        reservation: false,
    },{
        id: 1,
        name: "Jan",
        lastName: "Kowalski",
        ratingCourse: 5,
        ratingActive: 3,
        ratingCode: 4,
        ratingWork: 5,
        preferPlaceWork: "Biuro",
        cityWork: "Warszawa",
        contractType: "Umowa o pracę",
        expectedSalary: 8000,
        freePractice: "Tak",
        commercialExp: "6 miesięcy",
        reservation: false,
    },{
        id: 1,
        name: "Jan",
        lastName: "Kowalski",
        ratingCourse: 5,
        ratingActive: 3,
        ratingCode: 4,
        ratingWork: 5,
        preferPlaceWork: "Biuro",
        cityWork: "Warszawa",
        contractType: "Umowa o pracę",
        expectedSalary: 8000,
        freePractice: "Tak",
        commercialExp: "6 miesięcy",
        reservation: false,
    },{
        id: 1,
        name: "Jan",
        lastName: "Kowalski",
        ratingCourse: 5,
        ratingActive: 3,
        ratingCode: 4,
        ratingWork: 5,
        preferPlaceWork: "Biuro",
        cityWork: "Warszawa",
        contractType: "Umowa o pracę",
        expectedSalary: 8000,
        freePractice: "Tak",
        commercialExp: "6 miesięcy",
        reservation: true,
    },
    {
        id: 1,
        name: "Jan",
        lastName: "Kowalski",
        ratingCourse: 5,
        ratingActive: 3,
        ratingCode: 4,
        ratingWork: 5,
        preferPlaceWork: "Biuro",
        cityWork: "Warszawa",
        contractType: "Umowa o pracę",
        expectedSalary: 8000,
        freePractice: "Tak",
        commercialExp: "6 miesięcy",
        reservation: false,
    },{
        id: 1,
        name: "Jan",
        lastName: "Kowalski",
        ratingCourse: 5,
        ratingActive: 3,
        ratingCode: 4,
        ratingWork: 5,
        preferPlaceWork: "Biuro",
        cityWork: "Warszawa",
        contractType: "Umowa o pracę",
        expectedSalary: 8000,
        freePractice: "Tak",
        commercialExp: "6 miesięcy",
        reservation: true,
    },{
        id: 1,
        name: "Jan",
        lastName: "Kowalski",
        ratingCourse: 5,
        ratingActive: 3,
        ratingCode: 4,
        ratingWork: 5,
        preferPlaceWork: "Biuro",
        cityWork: "Warszawa",
        contractType: "Umowa o pracę",
        expectedSalary: 8000,
        freePractice: "Tak",
        commercialExp: "6 miesięcy",
        reservation: false,
    },{
        id: 1,
        name: "Jan",
        lastName: "Kowalski",
        ratingCourse: 5,
        ratingActive: 3,
        ratingCode: 4,
        ratingWork: 5,
        preferPlaceWork: "Biuro",
        cityWork: "Warszawa",
        contractType: "Umowa o pracę",
        expectedSalary: 8000,
        freePractice: "Tak",
        commercialExp: "6 miesięcy",
        reservation: false,
    },{
        id: 1,
        name: "Jan",
        lastName: "Kowalski",
        ratingCourse: 5,
        ratingActive: 3,
        ratingCode: 4,
        ratingWork: 5,
        preferPlaceWork: "Biuro",
        cityWork: "Warszawa",
        contractType: "Umowa o pracę",
        expectedSalary: 8000,
        freePractice: "Tak",
        commercialExp: "6 miesięcy",
        reservation: true,
    }, {
        id: 1,
        name: "Jan",
        lastName: "Kowalski",
        ratingCourse: 5,
        ratingActive: 3,
        ratingCode: 4,
        ratingWork: 5,
        preferPlaceWork: "Biuro",
        cityWork: "Warszawa",
        contractType: "Umowa o pracę",
        expectedSalary: 8000,
        freePractice: "Tak",
        commercialExp: "6 miesięcy",
        reservation: false,
    },{
        id: 1,
        name: "Jan",
        lastName: "Kowalski",
        ratingCourse: 5,
        ratingActive: 3,
        ratingCode: 4,
        ratingWork: 5,
        preferPlaceWork: "Biuro",
        cityWork: "Warszawa",
        contractType: "Umowa o pracę",
        expectedSalary: 8000,
        freePractice: "Tak",
        commercialExp: "6 miesięcy",
        reservation: true,
    },{
        id: 1,
        name: "Jan",
        lastName: "Kowalski",
        ratingCourse: 5,
        ratingActive: 3,
        ratingCode: 4,
        ratingWork: 5,
        preferPlaceWork: "Biuro",
        cityWork: "Warszawa",
        contractType: "Umowa o pracę",
        expectedSalary: 8000,
        freePractice: "Tak",
        commercialExp: "6 miesięcy",
        reservation: false,
    },{
        id: 1,
        name: "Jan",
        lastName: "Kowalski",
        ratingCourse: 5,
        ratingActive: 3,
        ratingCode: 4,
        ratingWork: 5,
        preferPlaceWork: "Biuro",
        cityWork: "Warszawa",
        contractType: "Umowa o pracę",
        expectedSalary: 8000,
        freePractice: "Tak",
        commercialExp: "6 miesięcy",
        reservation: true,
    },{
        id: 1,
        name: "Jan",
        lastName: "Kowalski",
        ratingCourse: 5,
        ratingActive: 3,
        ratingCode: 4,
        ratingWork: 5,
        preferPlaceWork: "Biuro",
        cityWork: "Warszawa",
        contractType: "Umowa o pracę",
        expectedSalary: 8000,
        freePractice: "Tak",
        commercialExp: "6 miesięcy",
        reservation: true,
    },{
        id: 1,
        name: "Jan",
        lastName: "Kowalski",
        ratingCourse: 5,
        ratingActive: 3,
        ratingCode: 4,
        ratingWork: 5,
        preferPlaceWork: "Biuro",
        cityWork: "Warszawa",
        contractType: "Umowa o pracę",
        expectedSalary: 8000,
        freePractice: "Tak",
        commercialExp: "6 miesięcy",
        reservation: true,
    },{
        id: 1,
        name: "Jan",
        lastName: "Kowalski",
        ratingCourse: 5,
        ratingActive: 3,
        ratingCode: 4,
        ratingWork: 5,
        preferPlaceWork: "Biuro",
        cityWork: "Warszawa",
        contractType: "Umowa o pracę",
        expectedSalary: 8000,
        freePractice: "Tak",
        commercialExp: "6 miesięcy",
        reservation: true,
    },{
        id: 1,
        name: "Jan",
        lastName: "Kowalski",
        ratingCourse: 5,
        ratingActive: 3,
        ratingCode: 4,
        ratingWork: 5,
        preferPlaceWork: "Biuro",
        cityWork: "Warszawa",
        contractType: "Umowa o pracę",
        expectedSalary: 8000,
        freePractice: "Tak",
        commercialExp: "6 miesięcy",
        reservation: true,
    },{
        id: 1,
        name: "Jan",
        lastName: "Kowalski",
        ratingCourse: 5,
        ratingActive: 3,
        ratingCode: 4,
        ratingWork: 5,
        preferPlaceWork: "Biuro",
        cityWork: "Warszawa",
        contractType: "Umowa o pracę",
        expectedSalary: 8000,
        freePractice: "Tak",
        commercialExp: "6 miesięcy",
        reservation: true,
    },

]
